import {
  DOMAIN_MARKER_GLYPHS,
  DOMAIN_MARKER_ICON_SRCS,
  DOMAIN_REPORT_NUMBER_PREFIXES,
  EMPTY_INCIDENT_DOMAIN_HELPER,
  POTHOLE_MERGE_RADIUS_METERS,
} from "./mapIncidentDomainStartupConfig.js";
import { normalizeDomainKeyOrSlug } from "./mapReportParsingCoreSupport.js";

export {
  DOMAIN_MARKER_GLYPHS,
  DOMAIN_MARKER_ICON_SRCS,
  DOMAIN_REPORT_NUMBER_PREFIXES,
  EMPTY_INCIDENT_DOMAIN_HELPER,
  POTHOLE_MERGE_RADIUS_METERS,
} from "./mapIncidentDomainStartupConfig.js";

export const INCIDENT_DOMAIN_CORE_HELPERS = Object.freeze({
  potholes: Object.freeze({
    prefix: "pothole",
    usesCustomSubmitFlow: true,
    customSubmitFlowServiceSubmitFirst: true,
    serviceSubmitFunctionName: "submit-domain-report",
    shouldUseServiceSubmitFallbackMode: "message_or_code_match",
    shouldUseServiceSubmitFallbackCodes: Object.freeze(["22p02"]),
    shouldUseServiceSubmitFallbackSubstrings: Object.freeze([
      "row-level security",
      "violates row-level security policy",
      "permission denied",
      "not allowed",
      "forbidden",
      "invalid input syntax for type uuid",
      "22p02",
    ]),
    seededSourceTable: "potholes",
    reportsSourceTable: "pothole_reports",
    seededRealtimeChannel: "realtime-potholes",
    reportsRealtimeChannel: "realtime-pothole-reports",
    seededSelectFields: "id, ph_id, lat, lng, location_label, nearest_address, nearest_cross_street, nearest_landmark, created_at",
    reportsSelectFields: "id, pothole_id, lat, lng, note, report_number, created_at, reporter_user_id, reporter_name, reporter_phone, reporter_email",
    seededLookupField: "ph_id",
    reportsLookupField: "pothole_id",
    reportsLookupIdentityFields: Object.freeze(["reporter_user_id", "reporter_email"]),
    seededInsertLookupFailureMessage: "Pothole was created, but the new pothole location could not be loaded.",
    reportNumberPrefix: "PH",
    markerColor: "#8e24aa",
    adminExportUsesAllDomainReports: true,
    allowsRepeatAfterArchive: true,
    alreadyReportedMessage: "You already reported this pothole. You can report again after it is marked fixed.",
    fixedNoticeMessage: "Pothole marked fixed.",
    clearSelectedDomainMarkerOnFix: true,
    roadRequiredDefault: true,
    allowReportImagesDefault: true,
    submitGeoModeWhenNotRoad: "full",
    submitDebugSource: "submit:pothole",
    submitReportKeyHintFields: Object.freeze(["incident_id", "lightId", "pothole_id"]),
    persistenceIncidentIdMode: "normalized_persistence_id",
    persistenceIncidentIdRequireUuid: true,
    canonicalIncidentIdMode: "prefix_lookup",
    canonicalIncidentPrefix: "pothole",
    buildStatusDialogCompatMode: "lookup_official_marker",
    buildStatusDialogCompatExternalIdFields: Object.freeze(["external_id", "display_id", "ph_id"]),
    buildStatusDialogCompatExternalIdFallbackMode: "coords_display_id",
    buildStatusDialogCompatCompatMarkerIncidentField: "pothole_id",
    buildStatusDialogCompatCompatMarkerExternalIdField: "ph_id",
    resolveStatusDialogCompatTargetMode: "canonical_incident_official",
    resolveStatusDialogCompatTargetIncidentFields: Object.freeze(["incident_id", "pothole_id"]),
    usesCanonicalPrefixedId: true,
    suppressesGlyph: true,
    displayIdHintField: "ph_id",
    supportsIssueMetadata: false,
    fixTsMode: "incident_map",
    identityReportSource: "reportRows",
    identityLastFixMode: "incident_map",
    markerIconTextY: 15.3,
    markerIconTextSize: 14.5,
    markerIconHideFallbackGlyphWhenSourcePresent: true,
    normalizeSeededRecordMode: "seeded_record_with_external_display",
    normalizeSeededRecordExternalIdField: "ph_id",
    normalizeSeededRecordExternalDisplayFields: Object.freeze(["ph_id"]),
    normalizeReportRecordIncidentIdField: "pothole_id",
    normalizeReportRecordMode: "report_record_with_lookup_ts",
    submitConsentDisclosureText: "I agree to allow CityReport.io to submit this pothole report and my provided contact information to the city, utility, or other responsible agency on my behalf, and I confirm the submitted information is accurate to the best of my knowledge.",
    submitEmailDomainLabel: "Potholes",
    submitEmailIssueTypeFallback: "Pothole",
    authorizationDisclosureId: "potholes_submit_authorization",
    seededMarkerSeedIdMode: "incident_or_id",
    seededMarkerIdMode: "external_display_or_coords",
    seededMarkerIncidentIdMode: "canonical_from_seed_id",
    seededMarkerLastFixMode: "incident_map",
    seededMarkerSeedIdTargetFields: Object.freeze(["incident_id", "pothole_id"]),
    seededMarkerExternalDisplaySourceFields: Object.freeze(["external_id", "display_id", "ph_id"]),
    seededMarkerExternalDisplayTargetFields: Object.freeze(["external_id", "display_id"]),
    seededMarkerCopiedFieldNames: Object.freeze(["location_label"]),
    seededMarkerRowSeedIdFields: Object.freeze(["incident_id", "pothole_id"]),
    seededMarkerRowSeedIdRequireUuid: true,
    authorizationDisclosureExtraBefore: Object.freeze([
      {
        id: "potholes_vehicle_damage_notice",
        title: "Vehicle damage notice",
        body: "If you need to report damage to your vehicle from a pothole, you will need to file a police report as soon as possible, then bring this information to the City Manager's Office.",
        required_acknowledgement: false,
        display_position: "before_form",
      },
    ]),
    submitReportPayloadIncidentIdField: "pothole_id",
    customSubmitFlowInitialIncidentIdFields: Object.freeze(["incident_id", "pothole_id"]),
    customSubmitFlowInitialExternalIdFields: Object.freeze(["lightId", "ph_id", "external_id", "display_id"]),
    submitReportPayloadIncidentIdNormalizeMode: "persistence_incident_id",
    serviceSubmitPayloadIncidentIdField: "pothole_id",
    serviceSubmitPayloadIncidentIdNormalizeMode: "persistence_incident_id",
    serviceSubmitPayloadExternalIdField: "ph_id",
    serviceSubmitPayloadLocationLabelField: "location_label",
    serviceSubmitPayloadAddressField: "nearest_address",
    serviceSubmitPayloadCrossStreetField: "nearest_cross_street",
    serviceSubmitPayloadLandmarkField: "nearest_landmark",
    serviceSubmitPayloadCreatedByField: "created_by",
    serviceSubmitResultSeededField: "pothole",
    serviceSubmitResultReportField: "report",
    serviceSubmitResultIncidentIdField: "id",
    serviceSubmitResultExternalIdField: "ph_id",
    locationInsertPayloadExternalIdField: "ph_id",
    locationInsertPayloadLocationLabelField: "location_label",
    locationInsertPayloadCreatedByField: "created_by",
    normalizeSubmitGeoCacheIncidentIdMode: "normalized_persistence_id",
    insertedLocationRecordExternalIdField: "ph_id",
    insertedLocationIdsIncidentIdField: "id",
    insertedLocationIdsExternalIdField: "ph_id",
    savedReportRecordIncidentIdField: "pothole_id",
    applyPersistedLocationCacheStateMode: "patch_seeded_and_report_rows",
    applyPersistedLocationCacheStateSeededLookupField: "id",
    applyPersistedLocationCacheStateReportLookupFieldMode: "incident_or_domain_report_id",
    resolveNearbySubmitIncidentExternalIdField: "ph_id",
    applyPersistedLocationCacheStateLocationLabelField: "location_label",
    applyPersistedLocationCacheStateAddressField: "nearest_address",
    applyPersistedLocationCacheStateCrossStreetField: "nearest_cross_street",
    applyPersistedLocationCacheStateIntersectionField: "nearest_intersection",
    applyPersistedLocationCacheStateLandmarkField: "nearest_landmark",
    resolveNearbySubmitIncidentMode: "nearest_seeded_row_if_missing_incident",
    resolveNearbySubmitIncidentIdField: "id",
    resolveNearbySubmitIncidentRadiusMeters: POTHOLE_MERGE_RADIUS_METERS,
    reportLookupFallbackDataMode: "local_payload_with_timestamp",
    buildIncidentRowsMode: "canonical_incident_rows_from_lookup",
  }),
  water_drain_issues: Object.freeze({
    prefix: "water_drain_issues",
    reportNumberPrefix: "WD",
    markerColor: "#0288d1",
    adminExportUsesAllDomainReports: true,
    allowsRepeatAfterArchive: true,
    submitIdentityGuard: true,
    submitUsesCanonicalIncidentId: true,
    submitFallbackIncidentPrefix: "water_main",
    persistIssueTypeToLocationCache: true,
    defaultIssueLabel: "Water / Drain Issue",
    alreadyReportedMessage: "You already reported this water/drain issue. You can report again after it is marked fixed.",
    allowReportImagesDefault: true,
    suppressesGlyph: true,
    displayIdHintField: "wd_id",
    builtInDisplayIdMode: "coords_hashed_from_incident",
    prefersConfiguredIssueLabel: true,
    snapshotAliases: Object.freeze(["streetlights", "water_main"]),
    storedIssueValueStateField: "issue_type",
    storedIssueValueNoteParserMode: "tag_alias_with_keyword_map",
    storedIssueValueNoteParserAliases: Object.freeze(["Water Issue"]),
    storedIssueValueNoteParserKeywordValueMap: Object.freeze([
      Object.freeze({ value: "sewer_backup", matchAny: Object.freeze(["sewer"]) }),
      Object.freeze({ value: "storm_drain_clog", matchAny: Object.freeze(["storm drain", "drain blocked", "flood"]) }),
    ]),
    storedIssueValueRawTypeNormalizerMode: "report_type",
    fixedNoticeMessage: "Water / Drain issue marked fixed.",
    clearSelectedDomainMarkerOnFix: true,
    submitDisclosureText: "Submitting a report through CityReport helps notify the city, but it does not guarantee receipt, review, response, or acceptance as legal notice. Sewer, storm, or drainage issues may require immediate direct contact with the city or utility. For emergencies, call 911.",
    submitConsentDisclosureText: "I agree to allow CityReport.io to submit this water or drainage issue and my provided contact information to the city, utility, or other responsible agency on my behalf, and I confirm the submitted information is accurate to the best of my knowledge.",
    submitEmailDomainLabel: "Water / Drain",
    submitEmailIssueTypeFallback: "Water / Drain Issue",
    canonicalIncidentIdMode: "lookup_or_light_id",
    normalizeSubmitTargetLocationLabelField: "location_label",
    applyPersistedLocationCacheStateMode: "patch_record_state_map",
    persistedRecordStateSourceTable: "water_drain_incidents",
    persistedRecordStateRealtimeChannel: "realtime-water-drain-incidents",
    persistedRecordStateSelectFields: "incident_id, wd_id, issue_type, lat, lng, nearest_address, nearest_cross_street, nearest_landmark, geo_updated_at, updated_at",
    persistedRecordStateOrderField: "updated_at",
    applyPersistedLocationCacheStateRecordIdField: "wd_id",
    applyPersistedLocationCacheStateIssueTypeField: "issue_type",
    applyPersistedLocationCacheStateAddressField: "nearest_address",
    applyPersistedLocationCacheStateCrossStreetField: "nearest_cross_street",
    applyPersistedLocationCacheStateLandmarkField: "nearest_landmark",
    buildMarkerCollectionRowIncidentField: "light_id",
    buildMarkerCollectionRowFallbackIdMode: "coords_light_id",
    buildMarkerCollectionCanonicalIncidentIdMode: "cluster_majority_lookup_id",
    buildMarkerCollectionDisplayIdMode: "coords_hashed_from_incident",
    buildMarkerCollectionLastFixTsMode: "light_id_map",
    authorizationDisclosureId: "water_drain_submit_authorization",
  }),
  street_signs: Object.freeze({
    prefix: "street_signs",
    markerGlyphMode: "option_type_glyph",
    seededSourceTable: "official_signs",
    seededSelectFields: "id, sign_type, lat, lng, active",
    seededStaticFilters: Object.freeze([
      Object.freeze({ field: "active", value: true }),
    ]),
    reportNumberPrefix: "SS",
    markerColor: "#1e88e5",
    usesMappedCenter: true,
    adminMappingQueueVariant: "official_sign",
    mappedAssetUnitLabel: "Sign",
    queuedAssetLabels: Object.freeze({
      queuedLabel: "Queued sign",
      deleteLabel: "Delete sign",
    }),
    fixedNoticeMessage: "Street sign issue marked fixed.",
    clearSelectedDomainMarkerOnFix: true,
    seededMarkerSeedIdMode: "id",
    seededMarkerIdMode: "seed_id",
    seededMarkerIncidentIdMode: "seed_id",
    seededMarkerLastFixMode: "max_light_or_fixed",
    seededMarkerStaticFields: Object.freeze({ isOfficial: true }),
    seededMarkerCopiedFieldNames: Object.freeze(["nearest_address", "nearest_cross_street", "nearest_landmark"]),
    seededMarkerNormalizedCopyFields: Object.freeze([
      Object.freeze({
        sourceField: "sign_type",
        targetField: "sign_type",
        mode: "lowercase_or_default",
        defaultValue: "other",
      }),
    ]),
    seededMarkerRowSeedIdFields: Object.freeze(["light_id", "incident_id"]),
  }),
  power_outage: Object.freeze({
    prefix: "power_outage",
    reportNumberPrefix: "PO",
    markerColor: "#d32f2f",
  }),
  water_main: Object.freeze({
    prefix: "water_main",
    reportNumberPrefix: "WM",
    markerColor: "#1e88e5",
  }),
});

export function getIncidentDomainCoreHelperShared(domainKeyRaw) {
  const domainKey = normalizeDomainKeyOrSlug(domainKeyRaw, { allowUnknown: true });
  if (!domainKey) return EMPTY_INCIDENT_DOMAIN_HELPER;
  return INCIDENT_DOMAIN_CORE_HELPERS[domainKey] || EMPTY_INCIDENT_DOMAIN_HELPER;
}

export function incidentDomainCoreHelperKeysForConfiguredFieldShared(fieldName) {
  const field = String(fieldName || "").trim();
  if (!field) return [];
  return Object.entries(INCIDENT_DOMAIN_CORE_HELPERS)
    .filter(([, helper]) => {
      const value = helper?.[field];
      if (Array.isArray(value)) return value.length > 0;
      if (typeof value === "object" && value) return Object.keys(value).length > 0;
      return Boolean(String(value || "").trim());
    })
    .map(([domainKey]) => domainKey);
}
