export const RUNTIME_DOMAIN_META = {
  domainTypeByDomain: new Map(),
  reportPrefixByDomain: new Map(),
  iconSrcByDomain: new Map(),
  iconRenderModeByDomain: new Map(),
  iconTintModeByDomain: new Map(),
  iconTintColorByDomain: new Map(),
  highConfidenceIconTintModeByDomain: new Map(),
  highConfidenceIconTintColorByDomain: new Map(),
  labelByDomain: new Map(),
  markerColorByDomain: new Map(),
  publicVisibilityMinReportsByDomain: new Map(),
  highConfidenceMinReportsByDomain: new Map(),
  highConfidenceMarkerColorByDomain: new Map(),
  rawIssueTypesByDomain: new Map(),
  rawTypeOptionsByDomain: new Map(),
  issueTypesByDomain: new Map(),
  typeOptionsByDomain: new Map(),
  disclosuresByDomain: new Map(),
  allowReportImagesByDomain: new Map(),
  roadRequiredByDomain: new Map(),
  parkRequiredByDomain: new Map(),
};
