import React, { memo } from "react";
import MapLazyDesktopOverlay from "./mapLazyDesktopOverlay.jsx";

export default memo(function MapLazyDesktopOverlayBridge({
  mapHeaderTheme,
  titleLogoError,
  titleLogoSrc,
  titleLogoAlt,
  setTitleLogoError,
  environmentGuardrailLabel,
  organizationDisplayName,
  desktopAccountMenuAnchorRef,
  session,
  handleAccountMenuToggle,
  nudgeMapZoom,
  showMapNotificationsIcon,
  showMapAlertIcon,
  showMapEventIcon,
  viewerIdentityKey,
  hasMapSession,
  notificationsWindowOpen,
  alertsWindowOpen,
  eventsWindowOpen,
  residentNotificationsUnreadCount,
  mapAlertsUnreadCount,
  mapEventsUnreadCount,
  setAdminDomainMenuOpen,
  setAdminToolboxOpen,
  setNotificationsWindowOpen,
  setEventsWindowOpen,
  setAlertsWindowOpen,
  setAccountMenuOpen,
  prefersDarkMode,
  isAggregatedReportingDomain,
  canOpenDomainReports,
  canOpenAdminReports,
  openMyReports,
  openOpenReports,
  openReportsInViewLabel,
  openReportsInViewCount,
  inViewCounterColor,
  inViewCounterBorder,
  inViewCounterBg,
  isStreetlightsLayerActive,
  isSavedStreetlightFilterOn,
  isUtilityStreetlightFilterOn,
  streetlightPersonalInViewStats,
  toggleStreetlightInViewFilter,
  isAdmin,
  openAbuseFlagSummary,
  setModerationFlagsOpen,
}) {
  return (
    <MapLazyDesktopOverlay
      mapHeaderTheme={mapHeaderTheme}
      titleLogoError={titleLogoError}
      titleLogoSrc={titleLogoSrc}
      titleLogoAlt={titleLogoAlt}
      onTitleLogoError={() => setTitleLogoError(true)}
      environmentGuardrailLabel={environmentGuardrailLabel}
      organizationDisplayName={organizationDisplayName}
      desktopAccountMenuAnchorRef={desktopAccountMenuAnchorRef}
      session={session}
      onAccountMenuToggle={handleAccountMenuToggle}
      toolRailProps={{
        nudgeMapZoom,
        showMapNotificationsIcon,
        showMapAlertIcon,
        showMapEventIcon,
        viewerIdentityKey,
        hasMapSession,
        notificationsWindowOpen,
        alertsWindowOpen,
        eventsWindowOpen,
        residentNotificationsUnreadCount,
        mapAlertsUnreadCount,
        mapEventsUnreadCount,
        setAdminDomainMenuOpen,
        setAdminToolboxOpen,
        setNotificationsWindowOpen,
        setEventsWindowOpen,
        setAlertsWindowOpen,
        setAccountMenuOpen,
        prefersDarkMode,
      }}
      statusChipProps={{
        isAggregatedReportingDomain,
        canOpenDomainReports,
        canOpenAdminReports,
        openMyReports,
        openOpenReports,
        openReportsInViewLabel,
        openReportsInViewCount,
        inViewCounterColor,
        inViewCounterBorder,
        inViewCounterBg,
        isStreetlightsLayerActive,
        isSavedStreetlightFilterOn,
        isUtilityStreetlightFilterOn,
        streetlightPersonalInViewStats,
        toggleStreetlightInViewFilter,
        isAdmin,
        openAbuseFlagSummary,
        setModerationFlagsOpen,
      }}
    />
  );
});
