import React, { memo } from "react";
import MapLazyWorkspaceHost from "./mapLazyWorkspaceHost.jsx";
import { RUNTIME_DOMAIN_META } from "./lib/mapRuntimeDomainMeta.js";

export default memo(function MapLazyWorkspaceHostBridge({
  secondaryVisible,
  markWorkingConfirmOpen,
  pendingWorkingLightId,
  setPendingWorkingLightId,
  setIsWorkingConfirmOpen,
  submitIsWorking,
  incidentRepairConfirmOpen,
  pendingIncidentRepairId,
  pendingIncidentRepairDomainKey,
  closeIncidentRepairConfirmDialog,
  submitIncidentRepairConfirmation,
  utilityReportDialogOpen,
  pendingUtilityReportReference,
  setPendingUtilityReportReference,
  pendingUtilityReportLightId,
  closeUtilityReportDialog,
  markUtilityReportedForViewer,
  openConfiguredNotice,
  markFixedConfirmOpen,
  pendingIncidentLabel,
  pendingIncidentCurrentState,
  pendingIncidentDomainKey,
  pendingIncidentNextState,
  setPendingIncidentNextState,
  setPendingIncidentActionType,
  markFixedNote,
  setMarkFixedNote,
  markFixedSubmitting,
  markFixedImageFile,
  markFixedImagePreviewUrl,
  setMarkFixedImageFile,
  pendingIncidentPin,
  setPendingIncidentPin,
  pendingIncidentStatusError,
  setPendingIncidentStatusError,
  submitPendingIncidentAction,
  resetMarkFixedDialogState,
  moderationFlagsOpen,
  setModerationFlagsOpen,
  isAdmin,
  loadOpenAbuseFlagSummary,
  isMobile,
  mobileTabPageTopInset,
  mobileReportsPageBottomInset,
  notificationsWindowOpen,
  setNotificationsWindowOpen,
  residentFeedRuntimeReady,
  showMapNotificationsIcon,
  setResidentNotificationLocations,
  residentNotificationsRefreshToken,
  prefersDarkMode,
  useAppShellLayout,
  openResidentNotificationTarget,
  supabase,
  authReady,
  tenantReady,
  resolvedCommunityFeedTenantKey,
  communityFeedViewerKey,
  residentFeedRuntimeSupport,
  isMissingFunctionError,
  isMissingRelationError,
  isExpectedPermissionError,
  alertsWindowOpen,
  setAlertsWindowOpen,
  mapCommunityAlerts,
  mapCommunityFeedLoading,
  mapCommunityFeedError,
  alertsSessionNewKeys,
  focusedResidentAlertId,
  openCommunityFeedEditor,
  handleResidentAlertVisible,
  eventsWindowOpen,
  setEventsWindowOpen,
  mapCommunityEvents,
  eventsSessionNewKeys,
  focusedResidentEventId,
  handleResidentEventVisible,
  sessionUserId,
  communityFeedEditor,
  mapCommunityTopics,
  closeCommunityFeedEditor,
  loadMapCommunityFeed,
  openNotice,
  reports,
  officialLights,
  slIdByUuid,
  fixedLights,
  lastFixByLightId,
  actionsByLightId,
  session,
  profile,
  incidentStateByKey,
  reportKnownAssetIdSetsByDomain,
  cityBoundaryLoaded,
  isWithinAshtabulaCityLimits,
  reverseGeocodeRoadLabel,
  handleUtilityReportedChange,
  streetlightConfidenceByLightId,
  incidentRepairProgressByKey,
  persistedIncidentRepairConfirmedKeySet,
  canShowPublicRepairAction,
  requestIncidentRepairConfirmation,
  useNativeAppBehavior,
  incidentLocationCacheByKey,
  persistIncidentLocationCacheEntry,
  isSharedIncidentDomain,
  persistedIncidentRecordStateByDomain,
  configuredIncidentSeededByIdByDomain,
  configuredIncidentReportRowsByDomain,
  configuredIncidentSeededRowsByDomain,
  viewerIdentityKey,
  openIncidentStatusDialogForTarget,
  isTenantAssetBackedDomain,
  flyToLightAndOpen,
  myReportsOpen,
  closeMyReports,
  myReportsLaunchOptions,
  isReportsAdminView,
  isPublicRepairEnabledForDomain,
  myReportsDomain,
  myReportsAllReportsDomainOptions,
  setMyReportsDomain,
  setAdminReportDomain,
  setMyReportsDomainFilters,
  myReportsDomainFilters,
  toggleMyReportsDomainFilter,
  resetMyReportsDomainFilters,
  mapBounds,
  canToggleReportedByInMyReports,
  myReportsReportedByMode,
  setMyReportsReportedByMode,
  showAllInMyReports,
  canMutateAnyMyReportsSelection,
  canManageIncidentDomainRepairs,
  openReportsOpen,
  closeOpenReports,
  openReportsLaunchOptions,
  isPlatformAdmin,
  resolvedOpenReportsActiveDomain,
  canMutateAnyOpenReportsSelection,
  canOpenAdminReports,
  openReportsDomainOptions,
  openReportsDomainFilters,
  toggleOpenReportsDomainFilter,
  resetOpenReportsDomainFilters,
  isTenantOrganizationManagedIncidentDomain,
  shouldRenderStreetlightSelectionPopup,
  bulkMode,
  closeAnyPopup,
  clearUtilityReportedForViewer,
  isStreetlightsLayerActive,
  mappingMode,
  mapCenter,
  mapInteracting,
  mapZoom,
  openConfirmForLight,
  openMyReports,
  openUtilityReportDialogForLight,
  projectPopupPixel,
  selectedOfficialId,
  setDeleteOfficialConfirmOpen,
  setOfficialLights,
  setPendingDeleteOfficialLightId,
  setSelectedOfficialId,
  viewerSavedStreetlightLightIdSet,
  viewerStreetlightRingOpenIdSet,
  viewerUtilityReportedLightIdSet,
  utilityReportReferenceByLightId,
  shouldRenderIncidentDomainPopupWorkspace,
  isOrganizationManagedIncidentDomain,
  incidentDomainCanonicalIncidentId,
  incidentDrivenRowsByDomain,
  isPublicRepairEnabledForDomainFn,
  selectedDomainMarker,
  setPendingDeleteOfficialSignId,
  setDeleteOfficialSignConfirmOpen,
  setSelectedDomainMarker,
  adminReportDomain,
  getIncidentSnapshot,
  resolveIncidentDrivenFixTsForId,
  shouldRenderMapSelectionPopups,
  mappingQueue,
  openDomainReportFlow,
  openIncidentDomainMarker,
  removeFromMappingQueue,
  selectedIncidentStackMarker,
  selectedQueuedTempId,
  setSelectedIncidentStackMarker,
  setSelectedQueuedTempId,
  updateQueuedSignType,
}) {
  return (
    <MapLazyWorkspaceHost
      secondaryVisible={secondaryVisible}
      secondaryWorkspaceProps={{
        reportDialogs: {
          markWorkingConfirmOpen,
          pendingWorkingLightId,
          setPendingWorkingLightId,
          setIsWorkingConfirmOpen,
          submitMarkWorkingForViewer: submitIsWorking,
          incidentRepairConfirmOpen,
          pendingIncidentRepairId,
          pendingIncidentRepairDomainKey,
          closeIncidentRepairConfirmDialog,
          submitIncidentRepairConfirmation,
          utilityReportDialogOpen,
          pendingUtilityReportReference,
          setPendingUtilityReportReference,
          pendingUtilityReportLightId,
          closeUtilityReportDialog,
          markUtilityReportedForViewer,
          openConfiguredNotice,
          markFixedConfirmOpen,
          pendingIncidentLabel,
          pendingIncidentCurrentState,
          pendingIncidentDomainKey,
          pendingIncidentNextState,
          setPendingIncidentNextState,
          setPendingIncidentActionType,
          markFixedNote,
          setMarkFixedNote,
          markFixedSubmitting,
          markFixedImageFile,
          markFixedImagePreviewUrl,
          setMarkFixedImageFile,
          pendingIncidentPin,
          setPendingIncidentPin: (nextValue) => {
            setPendingIncidentPin(nextValue);
            if (pendingIncidentStatusError) setPendingIncidentStatusError("");
          },
          pendingIncidentStatusError,
          submitPendingIncidentAction,
          resetMarkFixedDialogState,
        },
        moderationWorkspace: {
          moderationFlagsOpen,
          setModerationFlagsOpen,
          isAdmin,
          loadOpenAbuseFlagSummary,
          isMobile,
          mobileTabPageTopInset,
          mobileReportsPageBottomInset,
        },
        residentFeedWorkspace: {
          notificationsWindowOpen,
          setNotificationsWindowOpen,
          residentFeedRuntimeReady,
          showMapNotificationsIcon,
          setResidentNotificationLocations,
          residentNotificationsRefreshToken,
          prefersDarkMode,
          useAppShellLayout,
          openResidentNotificationTarget,
          supabase,
          authReady,
          tenantReady,
          resolvedCommunityFeedTenantKey,
          communityFeedViewerKey,
          residentFeedRuntimeSupport,
          isMissingFunctionError,
          isMissingRelationError,
          isExpectedPermissionError,
          alertsWindowOpen,
          setAlertsWindowOpen,
          mapCommunityAlerts,
          mapCommunityFeedLoading,
          mapCommunityFeedError,
          alertsSessionNewKeys,
          focusedResidentAlertId,
          openCommunityFeedEditor,
          handleResidentAlertVisible,
          eventsWindowOpen,
          setEventsWindowOpen,
          mapCommunityEvents,
          eventsSessionNewKeys,
          focusedResidentEventId,
          handleResidentEventVisible,
          sessionUserId,
        },
        communityFeedEditorWorkspace: {
          communityFeedEditor,
          mapCommunityTopics,
          prefersDarkMode,
          useAppShellLayout,
          mobileTabPageTopInset,
          mobileReportsPageBottomInset,
          closeCommunityFeedEditor,
          supabase,
          resolvedCommunityFeedTenantKey,
          sessionUserId,
          loadMapCommunityFeed,
          openNotice,
        },
        reportsWorkspaceShared: {
          reports,
          officialLights,
          slIdByUuid,
          fixedLights,
          lastFixByLightId,
          actionsByLightId,
          session,
          profile,
          incidentStateByKey,
          reportKnownAssetIdSetsByDomainForExport: reportKnownAssetIdSetsByDomain,
          cityBoundaryLoaded,
          isWithinCityLimits: isWithinAshtabulaCityLimits,
          getStreetlightUtilityDetails: reverseGeocodeRoadLabel,
          onUtilityReportedChange: handleUtilityReportedChange,
          streetlightConfidenceByLightId,
          incidentRepairProgressByKey,
          persistedIncidentRepairConfirmedKeySet,
          canShowPublicRepairAction,
          onConfirmRepairIncident: requestIncidentRepairConfirmation,
          pageTopInset: mobileTabPageTopInset,
          pageBottomInset: mobileReportsPageBottomInset,
          preferAppShellBehavior: useNativeAppBehavior,
          incidentLocationCacheSeed: incidentLocationCacheByKey,
          persistIncidentLocationCacheEntry,
          isSharedIncidentDomain,
          persistedIncidentRecordStateByDomain,
          configuredIncidentSeededByIdByDomain,
          configuredIncidentReportRowsByDomain,
          configuredIncidentSeededRowsByDomain,
          viewerIdentityKey,
          openIncidentStatusDialogForTarget,
          isTenantAssetBackedDomain,
          flyToLightAndOpen,
          setPendingWorkingLightId,
          setIsWorkingConfirmOpen,
        },
        myReportsWorkspaceConfig: {
          open: myReportsOpen,
          onClose: closeMyReports,
          controllerMode: "my",
          launchOptions: myReportsLaunchOptions,
          isAdmin: true,
          allowReporterDetails: isReportsAdminView,
          publicRepairLifecycleEnabled: isPublicRepairEnabledForDomain(myReportsDomain),
          darkMode: prefersDarkMode,
          modalTitle: "My Reports",
          activeDomain: myReportsDomain,
          domainOptions: myReportsAllReportsDomainOptions,
          onSelectDomain: (domainKey) => {
            setMyReportsDomain(domainKey);
            setAdminReportDomain(domainKey);
            setMyReportsDomainFilters([domainKey]);
          },
          selectedDomains: myReportsDomainFilters,
          onToggleDomain: toggleMyReportsDomainFilter,
          onSelectAllDomains: resetMyReportsDomainFilters,
          mapBounds,
          canToggleReportedBy: canToggleReportedByInMyReports,
          reportedByMode: myReportsReportedByMode,
          onReportedByModeChange: setMyReportsReportedByMode,
          allowIncidentMutations: showAllInMyReports && canMutateAnyMyReportsSelection,
          canManageIncidentMutations: showAllInMyReports ? canManageIncidentDomainRepairs : null,
          showUpdateIncidentStatus: showAllInMyReports,
        },
        openReportsWorkspaceConfig: {
          open: openReportsOpen,
          onClose: closeOpenReports,
          controllerMode: "open",
          launchOptions: openReportsLaunchOptions,
          isAdmin: isReportsAdminView,
          allowReporterDetails: isReportsAdminView,
          showDeveloperDiagnostics: isPlatformAdmin,
          publicRepairLifecycleEnabled: isPublicRepairEnabledForDomain(resolvedOpenReportsActiveDomain),
          darkMode: prefersDarkMode,
          allowIncidentMutations: canMutateAnyOpenReportsSelection,
          canManageIncidentMutations: canManageIncidentDomainRepairs,
          modalTitle: canOpenAdminReports ? "Admin Reports" : "Domain Reports",
          activeDomain: resolvedOpenReportsActiveDomain,
          domainOptions: openReportsDomainOptions,
          onSelectDomain: setAdminReportDomain,
          selectedDomains: openReportsDomainFilters,
          onToggleDomain: toggleOpenReportsDomainFilter,
          onSelectAllDomains: resetOpenReportsDomainFilters,
          shouldIncludeDerivedSharedDomain: isTenantOrganizationManagedIncidentDomain,
        },
      }}
      streetlightPopupVisible={shouldRenderStreetlightSelectionPopup}
      streetlightPopupProps={{
        bulkMode,
        closeAnyPopup,
        clearUtilityReportedForViewer,
        isAdmin,
        isStreetlightsLayerActive,
        mappingMode,
        mapCenter,
        mapInteracting,
        mapZoom,
        officialLights,
        openConfirmForLight,
        openMyReports,
        openUtilityReportDialogForLight,
        prefersDarkMode,
        projectPopupPixel,
        reverseGeocodeRoadLabel,
        selectedOfficialId,
        session,
        setDeleteOfficialConfirmOpen,
        setIsWorkingConfirmOpen,
        setOfficialLights,
        setPendingDeleteOfficialLightId,
        setPendingWorkingLightId,
        setSelectedOfficialId,
        slIdByUuid,
        streetlightConfidenceByLightId,
        useAppShellLayout,
        utilityReportReferenceByLightId,
        viewerSavedStreetlightLightIdSet,
        viewerStreetlightRingOpenIdSet,
        viewerUtilityReportedLightIdSet,
      }}
      incidentDomainPopupVisible={shouldRenderIncidentDomainPopupWorkspace}
      incidentDomainPopupProps={{
        shared: {
          isOrganizationManagedIncidentDomain,
        },
        bulkMode,
        canManageIncidentDomainRepairs,
        canShowPublicRepairAction,
        incidentRepairProgressByKey,
        incidentDomainCanonicalIncidentId,
        incidentDrivenRowsByDomain,
        isAdmin,
        isPlatformAdmin,
        isPublicRepairEnabledForDomain: isPublicRepairEnabledForDomainFn,
        isReportsAdminView,
        mapCenter,
        mapInteracting,
        mapZoom,
        mappingMode,
        actionsByLightId,
        openDomainReportFlow,
        openIncidentStatusDialogForTarget,
        openMyReports,
        persistIncidentLocationCacheEntry,
        persistedIncidentRepairConfirmedKeySet,
        prefersDarkMode,
        resolveIncidentDrivenFixTsForId,
        requestIncidentRepairConfirmation,
        reverseGeocodeRoadLabel,
        slIdByUuid,
        projectPopupPixel,
        incidentLocationCacheByKey,
        selectedDomainMarker,
        openDeleteOfficialSignConfirm: (assetId) => {
          setPendingDeleteOfficialSignId(assetId);
          setDeleteOfficialSignConfirmOpen(true);
        },
        setSelectedDomainMarker,
        useAppShellLayout,
        adminReportDomain,
        getIncidentSnapshot,
        viewerIdentityKey,
        persistedIncidentRecordStateByDomain,
        configuredIncidentSeededByIdByDomain,
      }}
      selectionPopupsVisible={shouldRenderMapSelectionPopups}
      selectionPopupsProps={{
        shared: {
          isOrganizationManagedIncidentDomain,
        },
        bulkMode,
        canManageIncidentDomainRepairs,
        canShowPublicRepairAction,
        incidentRepairProgressByKey,
        incidentDomainCanonicalIncidentId,
        incidentDrivenRowsByDomain,
        isAdmin,
        isPlatformAdmin,
        isPublicRepairEnabledForDomain: isPublicRepairEnabledForDomainFn,
        isReportsAdminView,
        mapCenter,
        mapInteracting,
        mapZoom,
        mappingMode,
        mappingQueue,
        officialLights,
        actionsByLightId,
        openDomainReportFlow,
        openIncidentDomainMarker,
        openIncidentStatusDialogForTarget,
        openMyReports,
        openNotice,
        persistIncidentLocationCacheEntry,
        persistedIncidentRepairConfirmedKeySet,
        prefersDarkMode,
        removeFromMappingQueue,
        resolveIncidentDrivenFixTsForId,
        requestIncidentRepairConfirmation,
        reverseGeocodeRoadLabel,
        projectPopupPixel,
        incidentLocationCacheByKey,
        selectedIncidentStackMarker,
        selectedQueuedTempId,
        openDeleteOfficialSignConfirm: (assetId) => {
          setPendingDeleteOfficialSignId(assetId);
          setDeleteOfficialSignConfirmOpen(true);
        },
        setSelectedDomainMarker,
        setSelectedIncidentStackMarker,
        setSelectedQueuedTempId,
        slIdByUuid,
        updateQueuedSignType,
        useAppShellLayout,
        adminReportDomain,
        getIncidentSnapshot,
        runtimeDomainMeta: RUNTIME_DOMAIN_META,
        viewerIdentityKey,
        persistedIncidentRecordStateByDomain,
        configuredIncidentSeededByIdByDomain,
      }}
    />
  );
});
