import React, { memo } from "react";
import MapLazyMobileChrome from "./mapLazyMobileChrome.jsx";

export default memo(function MapLazyMobileChromeBridge({
  mapHeaderTheme,
  mobileHeaderMinHeight,
  mobileHeaderContentTopInset,
  mobileHeaderBottomInset,
  mobileTitleLogoSrc,
  titleLogoAlt,
  titleLogoError,
  mobileHeaderCopyMaxWidth,
  mobileHeaderCopyPadding,
  mobileHeaderCopyBottomPadding,
  mobileHeaderCopyTranslateY,
  mobileHeaderEyebrowSize,
  environmentGuardrailLabel,
  mobileHeaderGuardrailPadding,
  mobileHeaderGuardrailFontSize,
  mobileHeaderGuardrailMarginTop,
  mobileHeaderTitleSize,
  mobileHeaderTitleMarginTop,
  organizationDisplayName,
  session,
  profile,
  mobileTabPageTopInset,
  mobileReportsPageBottomInset,
  prefersDarkMode,
  tenant,
  openMyReports,
  setAccountMenuOpen,
  setAccountView,
  setNotificationPreferencesOpen,
  setFollowedLocationsOpen,
  setManageEditing,
  setManageOpen,
  setInfoMenuOpen,
  setCitySwitcherOpen,
  setContactUsOpen,
  signOut,
  setMobileHeaderMenuOpen,
  setLocationDiagnosticsOpen,
  tenantKeyValue,
  tenantScopedReadClient,
  showAdminTools,
  showMobileMapTabContent,
  accountMenuOpen,
  showNotificationPreferencesEntry,
  handleMobileTitleLogoError,
  handleToggleMobileHeaderMenu,
  mobileHeaderMenuOpen,
  mapType,
  locating,
  travelFollowMode,
  mobileMapToolButtonStyle,
  mobileMapLayerButtonStyle,
  mobilePrimaryLayerOptions,
  activeMapLayerKey,
  isStreetlightsLayerActive,
  canUseStreetlightBulk,
  incidentLayerDomainOptions,
  mobileIncidentDomainMenuOpen,
  allIncidentReportsOptionEnabled,
  hasExplicitIncidentMapFilter,
  activeIncidentMapFilterKeys,
  resolvedIncidentLayerOption,
  bulkMode,
  mappingMode,
  handleMobileToggleSatellite,
  handleMobileResetHeading,
  handleMobileLocate,
  handleMobileToggleTravelFollow,
  handleMobileRecenterHome,
  handleMobileSelectMapLayer,
  runMobileIncidentMenuAction,
  shouldIgnoreMobileIncidentMenuClick,
  handleMobileResetIncidentFilter,
  handleMobileToggleIncidentDomainFilter,
  handleMobileToggleBulkMode,
  handleMobileToggleMappingMode,
  isAggregatedReportingDomain,
  canOpenDomainReports,
  openReportsInViewLabel,
  openReportsInViewCount,
  inViewCounterColor,
  inViewCounterBorder,
  inViewCounterBg,
  isSavedStreetlightFilterOn,
  isUtilityStreetlightFilterOn,
  streetlightPersonalInViewStats,
  isAdmin,
  openAbuseFlagSummary,
  handleOpenMobileInViewReports,
  handleToggleSavedStreetlightInViewFilter,
  handleToggleUtilityStreetlightInViewFilter,
  handleOpenModerationFlags,
  mobileBottomRailOffset,
  bulkSelectedCount,
  saving,
  clearBulkSelection,
  openNotice,
  mapZoomRef,
  mapZoom,
  reportingMinZoom,
  openConfiguredNotice,
  closeAnyPopup,
  suppressPopupsSafe,
  setNote,
  setReportType,
  setStreetlightAreaPowerOn,
  setStreetlightHazardYesNo,
  setBulkConfirmOpen,
  bulkMaxLightsPerSubmit,
  mappingQueueLength,
  requestClearQueuedLights,
  confirmMappingQueue,
  mappingUnitLabel,
  mobileBottomRailHeight,
  mobileBottomRailSurfaceBg,
  mobileBottomRailColumnCount,
  useWideIosTabletShell,
  useAppShellLayout,
  useWideAppShellHeader,
  myReportsOpen,
  notificationsWindowOpen,
  alertsWindowOpen,
  eventsWindowOpen,
  accountTabActive,
  showMapNotificationsIcon,
  showMapAlertIcon,
  showMapEventIcon,
  residentNotificationsUnreadCount,
  mapAlertsUnreadCount,
  mapEventsUnreadCount,
  handleMobileBottomRailMapClick,
  handleMobileBottomRailReportsClick,
  handleMobileBottomRailNotificationsClick,
  handleMobileBottomRailAlertsClick,
  handleMobileBottomRailEventsClick,
  handleMobileBottomRailAccountClick,
}) {
  return (
    <MapLazyMobileChrome
      mobileChromeShared={{
        mapHeaderTheme,
        mobileHeaderMinHeight,
        mobileHeaderContentTopInset,
        mobileHeaderBottomInset,
        mobileTitleLogoSrc,
        titleLogoAlt,
        titleLogoError,
        mobileHeaderCopyMaxWidth,
        mobileHeaderCopyPadding,
        mobileHeaderCopyBottomPadding,
        mobileHeaderCopyTranslateY,
        mobileHeaderEyebrowSize,
        environmentGuardrailLabel,
        mobileHeaderGuardrailPadding,
        mobileHeaderGuardrailFontSize,
        mobileHeaderGuardrailMarginTop,
        mobileHeaderTitleSize,
        mobileHeaderTitleMarginTop,
        organizationDisplayName,
        session,
        profile,
        mobileTabPageTopInset,
        mobileReportsPageBottomInset,
        prefersDarkMode,
        tenant,
        openMyReports,
        setAccountMenuOpen,
        setAccountView,
        setNotificationPreferencesOpen,
        setFollowedLocationsOpen,
        setManageEditing,
        setManageOpen,
        setInfoMenuOpen,
        setCitySwitcherOpen,
        setContactUsOpen,
        signOut,
        setMobileHeaderMenuOpen,
        setLocationDiagnosticsOpen,
        tenantKey: tenantKeyValue,
        tenantScopedReadClient,
        showAdminTools,
        showMobileMapTabContent,
      }}
      topOverlayConfig={{
        accountMenuOpen,
        showNotificationPreferencesEntry,
        onTitleLogoError: handleMobileTitleLogoError,
        onMenuClick: handleToggleMobileHeaderMenu,
        mobileHeaderMenuOpen,
      }}
      toolChromeConfig={{
        mapType,
        prefersDarkMode,
        locating,
        travelFollowMode,
        mobileMapToolButtonStyle,
        mobileMapLayerButtonStyle,
        mobilePrimaryLayerOptions,
        activeMapLayerKey,
        isStreetlightsLayerActive,
        canUseStreetlightBulk,
        showAdminTools,
        incidentLayerDomainOptions,
        mobileIncidentDomainMenuOpen,
        allIncidentReportsOptionEnabled,
        hasExplicitIncidentMapFilter,
        activeIncidentMapFilterKeys,
        resolvedIncidentLayerOption,
        bulkMode,
        mappingMode,
        onToggleSatellite: handleMobileToggleSatellite,
        onResetHeading: handleMobileResetHeading,
        onLocate: handleMobileLocate,
        onToggleTravelFollow: handleMobileToggleTravelFollow,
        onRecenterHome: handleMobileRecenterHome,
        onSelectLayer: handleMobileSelectMapLayer,
        onRunMobileIncidentMenuAction: runMobileIncidentMenuAction,
        shouldIgnoreMobileIncidentMenuClick,
        onResetIncidentFilter: handleMobileResetIncidentFilter,
        onToggleIncidentDomainFilter: handleMobileToggleIncidentDomainFilter,
        onToggleBulkMode: handleMobileToggleBulkMode,
        onToggleMappingMode: handleMobileToggleMappingMode,
      }}
      statusChipConfig={{
        isAggregatedReportingDomain,
        canOpenDomainReports,
        openReportsInViewLabel,
        openReportsInViewCount,
        inViewCounterColor,
        inViewCounterBorder,
        inViewCounterBg,
        isStreetlightsLayerActive,
        isSavedStreetlightFilterOn,
        isUtilityStreetlightFilterOn,
        streetlightPersonalInViewStats,
        isAdmin,
        openAbuseFlagSummary,
        onOpenInViewReports: handleOpenMobileInViewReports,
        onToggleSavedStreetlightFilter: handleToggleSavedStreetlightInViewFilter,
        onToggleUtilityStreetlightFilter: handleToggleUtilityStreetlightInViewFilter,
        onOpenModerationFlags: handleOpenModerationFlags,
      }}
      bulkActionBarConfig={{
        canUseStreetlightBulk,
        bulkMode,
        mobileBottomRailOffset,
        bulkSelectedCount,
        saving,
        clearBulkSelection,
        openNotice,
        mapZoomRef,
        mapZoom,
        reportingMinZoom,
        openConfiguredNotice,
        closeAnyPopup,
        suppressPopupsSafe,
        setNote,
        setReportType,
        defaultStreetlightIssueValue: "",
        setStreetlightAreaPowerOn,
        setStreetlightHazardYesNo,
        setBulkConfirmOpen,
        bulkMaxLightsPerSubmit,
      }}
      mappingActionBarProps={{
        mappingMode,
        mappingQueueLength,
        mobileBottomRailOffset,
        requestClearQueuedLights,
        confirmMappingQueue,
        mappingUnitLabel,
      }}
      bottomRailProps={{
        mobileBottomRailHeight,
        mobileBottomRailSurfaceBg,
        mobileBottomRailColumnCount,
        useWideIosTabletShell,
        useAppShellLayout,
        useWideAppShellHeader,
        showMobileMapTabContent,
        myReportsOpen,
        notificationsWindowOpen,
        alertsWindowOpen,
        eventsWindowOpen,
        accountTabActive,
        showMapNotificationsIcon,
        showMapAlertIcon,
        showMapEventIcon,
        residentNotificationsUnreadCount,
        mapAlertsUnreadCount,
        mapEventsUnreadCount,
        prefersDarkMode,
        onMapClick: handleMobileBottomRailMapClick,
        onReportsClick: handleMobileBottomRailReportsClick,
        onNotificationsClick: handleMobileBottomRailNotificationsClick,
        onAlertsClick: handleMobileBottomRailAlertsClick,
        onEventsClick: handleMobileBottomRailEventsClick,
        onAccountClick: handleMobileBottomRailAccountClick,
      }}
    />
  );
});
